name: Butler Push
on: push

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feature/structure'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Prepare Deploy Files
      uses: canastro/copy-file-action@master
      with:
        source: "Purpose.html"
        target: "dist/index.html"
    - name: Deploy to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html5
        ITCH_GAME: ${{ github.ref == 'refs/heads/master' && 'purpose' || 'purpose-dev' }}
        ITCH_USER: infernochris
        PACKAGE: dist
        VERSION: ${{ env.GITHUB_REF_NAME }}
    - name: Trigger Discord Webhook
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}