name: Lint, Copy, & Deploy
on: push

jobs:
  jsLint:
    name: Run Javascript Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Cache npm Directory
        uses: c-hive/gha-npm-cache@v1
      - name: npm Install
        run: npm ci
      - name: Lint Javascript
        run: npm run jslint
  cssLint:
    name: Run CSS Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Cache npm Directory
        uses: c-hive/gha-npm-cache@v1
      - name: npm Install
        run: npm ci
      - name: Lint CSS
        run: npm run csslint
  copy:
    name: Copy Files To dist
    needs: [jsLint, cssLint]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Cache npm Directory
        uses: c-hive/gha-npm-cache@v1
      - name: npm Install
        run: npm ci
      - name: Copy Files To dist
        run: npm run copy
  deploy:
    name: Deploy to itch.io
    needs: copy
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Minify JS & CSS dist files
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: true
        directory: 'dist'
    - name: Deploy to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html5
        ITCH_GAME: ${{ contains(github.ref, 'refs/tags/') && 'purpose' || 'purpose-dev' }}
        ITCH_USER: infernochris
        PACKAGE: dist
        VERSION: ${{ env.GITHUB_REF_NAME }}
